name: Build and Deploy Lambda with SAM

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/application*.properties'
      - '**/db/migration/**'
      - 'maze-solver-server/template.yaml'
      - '.github/workflows/lambda-deploy.yml'
      # Explicitly exclude documentation changes
      - '!**/*.md'
      - '!**/*.txt'
      - '!**/*.puml'
      - '!**/LICENSE'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        working-directory: ./maze-solver-server
        run: |
          # Skip tests during SAM build using MAVEN_OPTS
          MAVEN_OPTS="-DskipTests=true" sam build --skip-pull-image \
            --parameter-overrides \
            DbUrl=${{ secrets.DB_URL }} \
            DbUsername=${{ secrets.DB_USERNAME }} \
            DbPassword=${{ secrets.DB_PASSWORD }}

      - name: SAM Deploy
        working-directory: ./maze-solver-server
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name maze-solver-server \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            DbUrl=${{ secrets.DB_URL }} \
            DbUsername=${{ secrets.DB_USERNAME }} \
            DbPassword=${{ secrets.DB_PASSWORD }}
